const API_URL = "http://127.0.0.1:8000";
let token = localStorage.getItem("access_token");
let accountNumber = null;
const $ = id => document.getElementById(id);
function showView(id){["login-view","register-view","dashboard-view"].forEach(v=>$(v).classList.toggle("hidden",v!==id))}
function msg(id,text,ok=false){$(id).textContent=text||"";$(id).style.color=ok?"#15803d":"#dc2626"}
async function request(path,options={}){const headers=options.headers||{};headers["Content-Type"]="application/json";if(token)headers.Authorization=`Bearer ${token}`;const r=await fetch(`${API_URL}${path}`,{...options,headers});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={detail:t}}if(!r.ok)throw new Error(d.detail||"Ocorreu um erro.");return d}
$("show-register").onclick=()=>showView("register-view");$("show-login").onclick=()=>showView("login-view");
$("login-form").onsubmit=async e=>{e.preventDefault();msg("login-message","");try{const d=await request("/Login",{method:"POST",body:JSON.stringify({email:$("login-email").value,senha:$("login-senha").value})});token=d.access_token;localStorage.setItem("access_token",token);showView("dashboard-view");await carregarUsuario()}catch(err){msg("login-message",err.message)}};
$("register-form").onsubmit=async e=>{e.preventDefault();msg("register-message","");const dados={nome:$("register-nome").value,email:$("register-email").value,cpf:$("register-cpf").value.replace(/\D/g,""),senha:$("register-senha").value};try{await request("/cadastro",{method:"POST",body:JSON.stringify(dados)});msg("register-message","Cadastro realizado com sucesso!",true);$("register-form").reset();setTimeout(()=>showView("login-view"),900)}catch(err){msg("register-message",err.message)}};
async function carregarUsuario(){try{const payload=JSON.parse(atob(token.split(".")[1]));const id=payload.sub;const u=await request(`/usuario/${id}`);$("welcome").textContent=`Olá, ${u.nome} | CPF: ${u.cpf}`;accountNumber=1000+Number(id);$("account-number").textContent=accountNumber;await atualizarSaldo();await atualizarExtrato()}catch{logout()}}
async function atualizarSaldo(){try{$("balance").textContent=money((await request(`/saldo/${accountNumber}`)).Saldo)}catch{$("balance").textContent="Erro"}}
$("refresh-balance").onclick=atualizarSaldo;
$("deposit-form").onsubmit=async e=>{e.preventDefault();msg("deposit-message","");try{const d=await request(`/deposito/${accountNumber}?valor=${encodeURIComponent($("deposit-value").value)}`,{method:"POST"});msg("deposit-message",`Depósito realizado. Saldo: ${money(d.novo_saldo)}`,true);e.target.reset();await atualizarSaldo();await atualizarExtrato()}catch(err){msg("deposit-message",err.message)}};
$("withdraw-form").onsubmit=async e=>{e.preventDefault();msg("withdraw-message","");try{const d=await request(`/saque/${accountNumber}?valor=${encodeURIComponent($("withdraw-value").value)}`,{method:"POST"});msg("withdraw-message",`Saque realizado. Saldo: ${money(d.novo_saldo)}`,true);e.target.reset();await atualizarSaldo();await atualizarExtrato()}catch(err){msg("withdraw-message",err.message)}};
$("transfer-form").onsubmit=async e=>{e.preventDefault();msg("transfer-message","");try{const destino=$("transfer-account").value,valor=$("transfer-value").value;const d=await request(`/transferencia?conta_origem=${encodeURIComponent(accountNumber)}&conta_destino=${encodeURIComponent(destino)}&valor=${encodeURIComponent(valor)}`,{method:"POST"});msg("transfer-message",`Transferência realizada. Saldo: ${money(d.saldo_origem)}`,true);e.target.reset();await atualizarSaldo();await atualizarExtrato()}catch(err){msg("transfer-message",err.message)}};
async function atualizarExtrato(){try{const d=await request(`/extrato/${accountNumber}`);$("statement").innerHTML=d.length?d.map(x=>`<div class="transaction"><span><strong>${esc(x.tipo)}</strong><br>${date(x.data)}</span><strong>${money(x.valor)}</strong></div>`).join(""):"<div class='empty'>Nenhuma movimentação encontrada.</div>"}catch(err){$("statement").innerHTML=`<div class="empty">${esc(err.message)}</div>`}}
$("refresh-statement").onclick=atualizarExtrato;$("logout").onclick=logout;
function logout(){token=null;accountNumber=null;localStorage.removeItem("access_token");showView("login-view")};function money(v){return Number(v).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})};function date(v){return new Date(v).toLocaleString("pt-BR")};function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
$("register-cpf").oninput=e=>{let v=e.target.value.replace(/\D/g,"").slice(0,11);v=v.replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d{1,2})$/,"$1-$2");e.target.value=v};
if(token){showView("dashboard-view");carregarUsuario()}else showView("login-view");
