"""cria tabela de transacoes

Revision ID: 19423c317f6c
Revises: 55fe0c8cf35b
Create Date: 2026-10-02 13:52:15.849334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19423c317f6c'
down_revision: Union[str, Sequence[str], None] = '55fe0c8cf35b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_transacao', sa.String(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('conta_origem_id', sa.Integer(), nullable=True),
    sa.Column('conta_destino_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conta_destino_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['conta_origem_id'], ['conta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacao')
    # ### end Alembic commands ###
