"""adiciona protecao ao cpf

Revision ID: 836f9b4d2c4f
Revises: 19423c317f6c
Create Date: 2026-10-02 17:44:04.724193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836f9b4d2c4f'
down_revision: Union[str, Sequence[str], None] = '19423c317f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
